[package]
name = "example"
version = "0.0.1"
authors = ["Henning Meyer <tutmann@gmail.com>"]
edition = "2018"

description = "Shadertoy-like Html-Canvas implemented in Rust-WASM"
repository = "https://github.com/hmeyer/shadercanvas"
readme = "README.md"
keywords = ["shader", "glsl", "webgl", "canvas"]
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
shadercanvas = "0.0.3"
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
log = "0.4"
console_log = { version = "0.2", features = ["color"], optional = true }

[features]
default = ["console_log"]

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'HtmlCanvasElement',
  'MouseEvent',
  'WebGlBuffer',
  'WebGlVertexArrayObject',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlUniformLocation',
  'WebGlShader',
]
